stages:
  - build
  - deploy
  - publish

build:
  image: python:3.11
  stage: build
  tags:
    - aws
    - docker
  script:
    - pip install -r requirements.txt
    - mkdocs build
  artifacts:
    paths:
      - site/
    expire_in: 3 days
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

pages:
  stage: deploy
  image: ruby:2.3
  tags:
    - aws
    - docker
  dependencies:
    - build
  script:
    - mv site/ public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

publish:
  stage: publish
  image: python:3.11
  tags:
    - aws
    - docker
  script:
    - |-
      git remote | grep "public" && echo "public remote found, removing it..." && git remote remove public || echo "public remote not found"
    - |-
      git remote add public https://$GITHUB_USER:$GITHUB_TOKEN@$GITHUB_REPO
    - |-
      git branch --set-upstream-to public/main
    - |-
      git push --force 
  rules:
    - if: $CI_COMMIT_TAG =~ /publish-.*/
