# Project information
site_name: RingCentral Integrations
site_url: https://ringcentral.github.io/ringcentral-integration-docs

# Repository
# repo_url: https://github.com/ringcentral/ringcentral-integration-docs
# repo_name: ringcentral/ringcentral-integration-docs
# edit_uri: tree/main/docs
docs_dir: docs

theme:
  name: material
  custom_dir: overrides
  favicon: img/favicon.png
  logo: img/RingCentral_logo_color.png
  font:
    code: Roboto Mono
    text: Inter Tight
  features:
    - navigation.path
    # - navigation.sections
    - navigation.tabs
    - search.sharing
    - search.highlight
  palette:
    - scheme: default
      primary: custom
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ringcentral
extra_css:
  - extra.css

plugins:
  - privacy
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - exclude:
      regex:
        - "^#.*"
        - "inc/templates.md"

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - mdx_include
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: "2025 RingCentral, Inc. All rights reserved."

nav:
  - "Home": index.md
  - "RingCentral Archiver":
      - "Introduction": archiver/index.md
      - "User Notice": archiver/user-notice.md
      - "Enable Archiver": archiver/enable-archiver.md
      - "Admin Roles and Permissions": archiver/admin-roles-permissions.md
      - "User Roles and Permissions": archiver/user-roles-permissions.md
      - "System Requirements": archiver/system-requirements.md
      - "Linking Storages to Archiver": archiver/connect-storage.md
      - "Connect Dropbox": archiver/connect-dropbox.md
      - "Connect SFTP": archiver/connect-sftp.md
      - "Connect Google Drive": archiver/connect-gdrive.md
      - "Connect Box": archiver/connect-box.md
      - "Connect Smarsh": archiver/connect-smarsh.md
      - "Sync Options": archiver/sync-options.md
      - "Archive Logs":
          - "Overview": archiver/archive-logs.md
          - "Retry Mechanism": archiver/retry-mechanism.md
          - "Archive Status and Data Types": archiver/archive-status.md
      - "Notifications": archiver/notifications.md
      - "General Questions": archiver/questions.md
  - "CRM Integrations":
      - "RingCentral for HubSpot":
          - "Introduction": hubspot/index.md
          - "General Questions": hubspot/questions.md
          - "Migration Guide": hubspot/migration.md
      - "RingCentral for Salesforce":
          - "Introduction": salesforce/index.md
          - "General Questions": salesforce/questions.md
      - "RingCentral for Zendesk":
          - "Introduction": zendesk/index.md
          - "General Questions": zendesk/questions.md
  - "Productivity Integrations":
      - "RingCentral for MS Teams":
          - "Overview": msteams/index.md
          - "General Questions": msteams/questions.md
      - "RingCentral for Zapier":
          - "Overview": zapier/index.md
          - "Actions":
              - "Create Post": zapier/create-post.md
